### ISSUE TITLE
合并单元格后边框样式丢失

### ISSUE THREAD

**Issue by yanmin7857** [d-band/better-xlsx#113]
设置hMerge,vMergeh后 边框样式丢失了，应该如何处理？

**Comment by helloyou2012** [comment]
@yanmin7857 问题已修复，请更新到版本 `0.7.6`

合并单元格会使用当前 cell 的边框设置，比如当前 cell 是 A1，设置的 `vMerge=2, hMerge=2`，则 A1:C3 的边框以 A1 为主。

**Comment by yanmin7857** [comment]
感谢！
