### ISSUE TITLE
file size issue

### ISSUE THREAD

**Issue by pts011080** [d-band/better-xlsx#14]
I encountered some weird situation.
When I first write the buffer into file it show up the file size like 100MB.
But then it reduced to 15MB after I've open it at Excel and Save it without any modification.

And at the file preview (Mac OS) image, it show up some extra cell was created and store at the first few columns for every rows. It disappeared after the Save action. 

Any idea of this?

**Comment by helloyou2012** [comment]
@pts011080 default config `compression` is `null`, set it like this to compress:

```
import xlsx, { Zip } from 'better-xlsx';
Zip.defaults.compression = 'DEFLATE';
...
```
