### ISSUE TITLE
npm build  Unexpected character（lib.js）

### ISSUE THREAD

**Issue by chasonyang** [d-band/better-xlsx#17]
npm run build会报如下错误，目前没发现影响xlsx文件的生成：
ERROR in static/js/4.d1e69b299f63ca1b9e52.js from UglifyJs
Unexpected character  '`' [./~/better-xlsx/lib/lib.js:35,0][static/js/4.7a08c5e72fb9161e2056.js:1232,6]

我查看了lib.js文件，第35开始的代码如下
```
  41: `_(* #,##0_);_(* (#,##0);_(* "-"_);_(@_)`,
  42: `_("$"* #,##0_);_("$* (#,##0);_("$"* "-"_);_(@_)`,
  43: `_(* #,##0.00_);_(* (#,##0.00);_(* "-"??_);_(@_)`,
  44: `_("$"* #,##0.00_);_("$"* (#,##0.00);_("$"* "-"??_);_(@_)`,
```
环境如下：
win7
better-xlsx 版本0.3.2
使用了vue 2.3.4， webpack
工程使用的是vue的webpack模版（vue init webpack demo）

**Comment by helloyou2012** [comment]
模板字符串是 `ES2015` 开始支持的，应该是 `bable-loader` 没有处理 `node_modules` 下的文件，有两种方式可以解决：

1. babel-loader 修改一下 include
2. 用 dist 目录下的文件：`import xlsx from 'better-xlsx/dist/xlsx';`
