### ISSUE TITLE
是否可以合并单元格？

### ISSUE THREAD

**Issue by usercx** [d-band/better-xlsx#20]
想合并单元格，但并不知道如何去操作

**Comment by usercx** [comment]
或者有没有文档~~~~

**Comment by helloyou2012** [comment]
@usercx 可以的，这个例子就是合并单元格的例子：https://github.com/d-band/better-xlsx/blob/master/examples/simple.js

> `cell.hMerge=2` 水平合并 3 个单元格，`cell.vMerge=1` 垂直合并 两个单元格。
