### ISSUE TITLE
静态html放linux上，xlsx无法打开，文件格式错误

### ISSUE THREAD

**Issue by chasonyang** [d-band/better-xlsx#21]
目录的权限也试过设置为777
16.04虚拟机的浏览器打开后下载的文件拷贝出来也无法打开，同样的错误

环境：
chrome
webpack、vue
better-xlsx：0.3.3
ubuntu 14.04/16.04
apach2 /var/www/html目录与子目录均测试过

**Comment by helloyou2012** [comment]
@chasonyang 没太明白你的意思，是用 `better-xlsx` 生成的 Excel 文件无法打开么？是用什么软件打开失败呢？

**Comment by chasonyang** [comment]
生成的excel无法打开，在windows上面运行html，下载生成的excel，可以打开，把同样的html文件全部放linux上面，然后访问对应的域名或者ip，下载的excel无法打开，都是用 Microsoft Excel 2013去打开

**Comment by chasonyang** [comment]
@helloyou2012 抱歉，描述错误，windows上面一直是在npm run dev 模式下运行的，
访问npm run build得到的本地html文件，下载生成的excel，和linux（同样的html文件全部放linux上面，然后访问对应的域名或者ip，下载的excel）里面一样是无法打开的，
都是用 Microsoft Excel 2013打开

**Comment by chasonyang** [comment]
问题确定了，还是改为直接import的‘better-xlsx’，虽然还是会有之前提到的警告，但不影响excel的生成和打开 
问题相关 #17
