### ISSUE TITLE
Can you add a typescript definition for us?

### ISSUE THREAD

**Issue by MikyWang** [d-band/better-xlsx#39]
this tool is good , but I want use it in a typescript project, so Can you add a typescript definition for me and others who use typescipt?

**Comment by helloyou2012** [comment]
@MikyWang TypeScript now supports the `--allowJs` flag and you can use it.

**Comment by helloyou2012** [comment]
`tsconfig.json` like this:

```
{
  "compilerOptions": {
    "allowJs": true,
    "types": ["node"]
  }
}
```
