### ISSUE TITLE
Date formatting

### ISSUE THREAD

**Issue by robwold** [d-band/better-xlsx#40]
Given a cell of type datetime, how can I specify the format? Having looked at the source for cell.js, I tried hacking it by changing the format string in the lib.js numFmt[] object, but it doesn't produce the desired output. 

It's not even clear if this is working as intended. The format string in numFmt[22] that's being applied (by html2xlsx) is "'m/d/yy h:mm'" but my output is of the form "dd/mm/yyyy hh:mm".

**Comment by helloyou2012** [comment]
@robwold you can do it this way:

```
const cell = row.addCell();
cell.value = new Date();
cell.numFmt = 'dd/mm/yyyy hh:mm';
```

**Comment by robwold** [comment]
Thanks for the reply, but I'm not adding the cell manually- I'm using html2xlsx. So I need something like 
        htmlTo(myHtml,(err, file) => {
          if (err) return console.error(err);
          var outputPath = 'reports/'+req.body.filename + '.xlsx'
          file.saveAs()
            .pipe(fs.createWriteStream(myOutputFile))
    }

**Comment by helloyou2012** [comment]
```javascript
const sheet = file.sheet['SheetName']; // or file.sheets[0];
sheet.cell(row, col).numFmt = 'dd/mm/yyyy hh:mm';
```

**Comment by robwold** [comment]
Thanks for your help. This plus the docs page for this project gave me everything I needed.
