### ISSUE TITLE
One merge cell per Row

### ISSUE THREAD

**Issue by sleepwood** [d-band/better-xlsx#46]
我发现现版本一个单元行只允许存在一个合并单元格，如果有两个合并单元格同时存在，则第二个会消失不见，我希望在未来的版本中能添加多合并单元格支持的功能，或者能提供一下类似状况的解决方法。

After testing by the project,I found that better-xlsx only support one merge cell in one row,the second merge cell will disappear.I hope multiple merge cell will be support in future.

**Comment by helloyou2012** [comment]
Maybe you're using wrong, correct demo like this:

```
const xlsx = require('better-xlsx');
const file = new xlsx.File();
const sheet = file.addSheet('Sheet1');

const c11 = sheet.cell(0, 0);
const c13 = sheet.cell(0, 2);
const c15 = sheet.cell(0, 4);

c11.value = 'Merge A1 B1';
c11.hMerge = 1;

c13.value = 'Merge C1 D1';
c13.hMerge = 1;

c15.value = 'Merge E1 F1';
c15.hMerge = 1;
```
<img width="469" alt="screen shot 2017-12-31 at 7 12 23 pm" src="https://user-images.githubusercontent.com/1798364/34461145-3630d1d2-ee5e-11e7-8bda-525e5027a156.png">
