### ISSUE TITLE
能否把编译好的版本放出来啊？

### ISSUE THREAD

**Issue by 188007803** [d-band/better-xlsx#5]

**Comment by helloyou2012** [comment]
发布到 npm 上的是编译过的～

**Comment by 188007803** [comment]
噢！好的，谢谢！我是想在网页上引用，不是本地用，希望能够把 网页上的grid 导出为excel，这个库可以吗？ 谢谢！

**Comment by helloyou2012** [comment]
@188007803 理论上应该是可以的，下个版本加一下。目前你可以自己编译源码～

**Comment by 188007803** [comment]
自己编译总是出错，盼望下个版本有这个功能，我们可以简单的在网页上引入，就可以直接读取和生成excel文件了，不需要从服务器上生成excel再下载了。

**Comment by 188007803** [comment]
相信好多人都盼望有这个功能呢！作者加油啊！！赞一个！！！

**Comment by helloyou2012** [comment]
@188007803 已添加，见 `dist` 目录。需要依赖 `jszip`，完整 Demo 详见：https://github.com/d-band/better-xlsx/blob/master/examples/simple.html

**Comment by 188007803** [comment]
太好了，谢谢作者的无私奉献。这下方便多了。
