### ISSUE TITLE
生成的excel用Poi不能解析

### ISSUE THREAD

**Issue by zhangdarong** [d-band/better-xlsx#56]
生成的excel中的文件夹没有zip压缩，导致不能poi不能正常解析。

**Comment by helloyou2012** [comment]
@zhangdarong 已修复(version 0.6.0)，添加了 compress 配置项：

```
const type = 'nodebuffer';
const compress = true;
file.saveAs(type, compress)
```

**Comment by helloyou2012** [comment]
@zhangdarong [saveAs 文档](https://d-band.github.io/better-xlsx/class/src/file.js~File.html#instance-method-saveAs)
