### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by NikiSunshine** [d-band/better-xlsx#7]
Hi, I have some questions to ask, sorry to disturb. I have used your file to export excel successfully , but when I read the excel , the first sheet can't be read , and there is no data, and the workbook's length is one less. If you have time , please write back to me. Thank you.

**Comment by helloyou2012** [comment]
I wrote a demo, it is ok. Could you supply more details.

```
const xlsx = require('node-xlsx').default;
// Parse a file
const data = xlsx.parse('./examples/complex.xlsx');

console.log(JSON.stringify(data, null, '  '));

/*
[
  {
    "name": "Sheet1",
    "data": [
      [
        "Category",
        "Budget",
        "Actual",
        "Difference"
      ],
      [
        "Auto",
        "$200.00",
        "$90.00",
        "$110.00"
      ],
      [
        "Entertainment",
        "$200.00",
        "$32.00",
        "$168.00"
      ],
      [
        "Food",
        "$350.00",
        "$205.75",
        "$144.25"
      ],
      [
        "Home",
        "$300.00",
        "$250.00",
        "$50.00"
      ],
      [
        "Medical",
        "$100.00",
        "$35.00",
        "$65.00"
      ],
      [
        "Personal Items",
        "$300.00",
        "$80.00",
        "$220.00"
      ],
      [
        "Travel",
        "$500.00",
        "$350.00",
        "$150.00"
      ],
      [
        "Utilities",
        "$200.00",
        "$100.00",
        "$100.00"
      ],
      [
        "Other",
        "$50.00",
        "$60.00",
        "($10.00)"
      ],
      [
        "Total",
        "$2,200.00",
        "$1,202.75",
        "$997.25"
      ]
    ]
  }
]
 */
```

**Comment by NikiSunshine** [comment]
I used the same method as you did. But the file be exported to be read again still has a sheet less.

**Comment by NikiSunshine** [comment]
I tested three excel which was exported by better-xlsx. Same issue

**Comment by NikiSunshine** [comment]
The workbook has more than one sheet. And when I delete other sheets to leave the first one. The first one can be read.Or, it can't be read, I can only get the data from the second one on.

**Comment by helloyou2012** [comment]
@NikiSunshine , it is bug of `js-xlsx` see: https://github.com/SheetJS/js-xlsx/issues/445

**Comment by NikiSunshine** [comment]
But whatever js-xlsx, node-xlsx, and so on . It has the same question.

**Comment by helloyou2012** [comment]
@NikiSunshine , `node-xlsx` dependent on `js-xlsx`.
